---
# For a list of all rules, see here:  https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013: false

# MD024/Multiple headings with the same content
MD024: false

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD037/Spaces inside emphasis markers
MD037: false
