[tools]
actionlint = "1.7"
editorconfig-checker = "3"
"pipx:pre-commit" = { version = "4.6.1", uvx_args = "--with pre-commit-uv" }
shellcheck = "0.11"
shfmt = "3"
uv = "0.11.31"
zizmor = "1.28.0"

[settings]
idiomatic_version_file_enable_tools = [
]

[task_config]
includes = [
    "toolbox/mise/tasks/toml/*.toml",
    "toolbox/scripts",
]
