[tools]
actionlint = "1.7"
editorconfig-checker = "4.0.2"
"pipx:pre-commit" = { version = "4.6.2", uvx_args = "--with pre-commit-uv" }
shellcheck = "0.11"
shfmt = "3"
taplo = "0.10"
uv = "0.12.19"
zizmor = "1.30.1"

[settings]
idiomatic_version_file_enable_tools = [
]

[task_config]
includes = [
    "toolbox/mise/tasks/toml/*.toml",
    "toolbox/scripts",
]
