include = [
    "**/*.toml",
    "**/*.toml.jinja",
]

[formatting]

align_comments = true
allowed_blank_lines = 1
array_auto_expand = true
array_trailing_comma = true
column_width = 1
indent_string = "    "
reorder_arrays = false
reorder_keys = true
trailing_newline = true
