[tasks]
"lint:all" = [
    "ruff:lint",
    "pylint",
]
pylint = [
    "pylint:run",
]
"pylint:run" = "pylint kubesplit tests"
pyright = [
    "pyright:run",
]
"pyright:run" = "pyright"
"pytest:cov" = "pytest --cov src --cov-report=xml --cov-report=term-missing --cov-branch"
"ruff:fmt:check" = "ruff format --check"
"ruff:fmt:run" = "ruff format"
"ruff:lint" = "ruff check"
"ruff:lint:fix" = "ruff check --fix"
style = [
    "ruff:fmt:run",
]
test = "pytest"
"test:cov" = [
    "pytest:cov",
]
