extend = "ruff_defaults.toml"
# you can change this file, you should NOT remove the extend directive

[lint]

ignore = [
    "ANN001",
    "ANN201",
    "ANN204",
    "T201",
    "PTH100",
    "PTH103",
    "PTH110",
    "PTH112",
    "PTH113",
    "PTH118",
    "PTH123",
]
