extend = "ruff_defaults.toml"
# you can change this file, you should NOT remove the extend directive

[lint]

ignore = [
    "A001",
    "PT009",
    "PT027",
    "ANN001",
    "ANN201",
    "ANN204",
    "TC002",
    "T201",
    "C408",
    "PTH100",
    "PTH103",
    "PTH110",
    "PTH112",
    "PTH113",
    "PTH118",
    "PTH123",
    "PERF102",
    "PERF402",
    "SIM102",
    "SIM108",
    "SIM118",
    "EM101",
    "EM102",
    "PLR0912",
    "PLR0913",
    "PLR2004",
    "TRY003",
    "PTH123",
    "PYI024",
    "ERA001",
    "C901",
    "RET504",
    "D100",
    "D103",
    "D417",
    "INP001",
    "SLF001",
    "UP006",
    "UP015",
    "UP030",
    "UP032",
    "UP035",
    "RUF012",
]
