---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    owner: example
    example.com/generated-by: kustomize
    example.com/kustomize-component: rbac/developers
  name: example:node-viewer-developer
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: example:node-viewer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: peter.parker@example.com
