---
version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.4
commands:
  python-checks-version:
    description: Run python checks
    steps:
      - run:
          name: Install requirements
          command: |
            set -x
            pip install --user -r requirements_dev.txt
            sudo apt-get update
            sudo apt-get install bats
      - run:
          name: Run linters
          command: |
            set -x
            export PATH=$PATH:/home/circleci/.local/bin
            make lint
      - run:
          name: Run unit tests
          command: |
            set -x
            export PATH=$PATH:/home/circleci/.local/bin
            make test
#      - run:
#          name: Run integration tests
#          command: |
#            set -x
#            make integration-tests
      - run:
          name: Check that we can build a package
          command: |
            set -x
            export PATH=$PATH:/home/circleci/.local/bin
            echo -n $PYPIRC_B64 | base64 --decode > ~/.pypirc
            make clean dist dist-check
            rm ~/.pypirc

jobs:
  eclint:
    docker:
      - image: qima/eclint:circleci-2.8.1-7c65341
    steps:
      - checkout
      - run:
          name: Validate Editor Config rules
          command: |
            set -x
            ls -l
            git ls-files
            eclint check $(git ls-files)

  python36-checks:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - python-checks-version

  python37-checks:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - python-checks-version

  python38-checks:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - python-checks-version

  python-publish:
    docker:
      - image: circleci/python:3.7-stretch-node
    steps:
      - checkout
      - run: if git log -1 --pretty=%B | grep SKIP_DEPLOY; then circleci-agent step halt; fi
      - run:
          name: Install requirements
          command: |
            set -x
            python3 -m venv ~/.venv
            source ~/.venv/bin/activate
            pip install -r requirements_dev.txt
            export PATH=$PATH:/home/circleci/.local/bin
            echo -n $PYPIRC_B64 | base64 --decode > ~/.pypirc
            make clean dist release
            rm ~/.pypirc

  docker-build-and-push:
    docker:
      - image: circleci/golang:1.11.5-stretch-node
    steps:
      - checkout
      - run: if git log -1 --pretty=%B | grep SKIP_DEPLOY; then circleci-agent step halt; fi
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build FTW!
          command: |
            set -x
            docker version
            make docker-build-pip
      - docker-publish/check
      - run:
          name: Push Exec Image
          command: |
            set -x
            make docker-push-pip

workflows:
  version: 2
  build_it:
    jobs:
      - eclint
      - python36-checks:
          requires:
            - eclint
      - python37-checks:
          requires:
            - eclint
      - python38-checks:
          requires:
            - eclint
      - python-publish:
          requires:
            - python36-checks
            - python37-checks
            - python38-checks
          filters:
            branches:
              only:
                - master
      - docker-build-and-push:
          requires:
            - python-publish
          filters:
            branches:
              only:
                - master
