apiVersion: v1
kind: Namespace
metadata:
  annotations:
    example.com/generated-by: kustomize
    example.com/kustomize-component: namespaces/integration
  labels:
    example.com/editors: developers
  name: apps-integration
