---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    owner: example
    example.com/generated-by: kustomize
    example.com/kustomize-component: namespaces/demo
  name: example:ns-demo-developer-binding
  namespace: apps-demo
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: peter.parker@example.com
