---
name: Workflows sanity checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  repo-checks:
    name: Check the repository github actions workflows
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # required by reviewdog's github-check reporter

    steps:
      - name: Checkout current branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283 # v1.73.1
        with:
          fail_level: error

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          advanced-security: false
          annotations: true
