---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    example.com/generated-by: kustomize
    example.com/kustomize-component: ingresses
  name: traefik-ingress-controller
  namespace: ingress-controllers
